# Generated by Django 5.0.1 on 2024-01-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('about', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
